#!/bin/bash
# system commands
alias \
  ls='ls -p --color=auto' \
  ll='ls -lah' \
  grep='grep --color=auto' \

alias \
  yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
  yta="yt -x -f bestaudio/best" \
  g='guix' \
  gp='echo $GUIX_PROFILE' \
  gg='git' \
  h='sudo herd' \
  xo='xdg-open'

# re-source
alias \
  rrb='source ~/.bashrc' \
  rrp='source $HOME/.config/shell/profile' \
  rra='source $HOME/.config/shell/aliases'

# easy check files
alias \
  aa='qz_get_aliases' \
  af='qz_get_functions'

# my functions
alias \
  gR='qz_guix_reconfigure' \
  gRd='qz_guix_reconfigure_debug' \
  gse='qz_guix_source_extra_profile'
  gsp='qz_guix_source_profile'
  dlsh='qz_download_scihub_doi'
