#!/bin/bash
qz_color() {
    echo -e "$1$2${qz_reset}"
}

qz_number_lines() {
    awk '{print NR" "$0}';
}

qz_reverse() {
    qz_number_lines | sort -k1 -n -r | sed 's/^[^ ]* //g';
}

# guix reconfigure, and debug to the repl
qz_guix_reconfigure_debug()  {
    sudo -E guix repl -L "$HOME/.config/guix" $@;
}

qz_guix_reconfigure()  {
    sudo -E guix system \
        -L "$HOME/.config/guix" \
        reconfigure "$HOME/.config/guix/qzdl/device/$(hostname).scm" $@;
}

# guix profile commands; make it easy to switch and check
qz_guix_source_extra_profile() {
    qz_guix_source_profile "$GUIX_EXTRA_PROFILES/$@";
}

qz_guix_source_profile() {
    export GUIX_PROFILE="$@"
    . "$GUIX_PROFILE/etc/profile";
}

qz_download_scihub_doi() {
    curl -O \
        $(curl -s http://sci-hub.tw/"$@" \
          | grep location.href \
          | grep -o http.*pdf);
}

qz_get_functions() {
  FILE="$QZ_FUNCTIONS"
  cat $FILE \
    | grep -on '^qz_.*()' \
    | awk -F: '{print file":"$1,$2}' file=$FILE
}

qz_get_aliases() {
  FILE="$QZ_ALIASES"
  cat $FILE \
    | grep -on "\s.*='.*'" \
    | awk -F: '{print file":"$1,$2}' file=$FILE
}
