#!/bin/bash
#
# environment variables, for /etc/environment
#
# to stow: <exec-shell-cmd "cd .. && sudo stow env -t /etc/">
#
#   █████  ███████  ██    ██
#  ██░░░██░░██░░░██░██   ░██
# ░███████ ░██  ░██░░██ ░██
# ░██░░░░  ░██  ░██ ░░████
# ░░██████ ███  ░██  ░░██
#  ░░░░░░ ░░░   ░░    ░░
 


PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

# Adds `~/.scripts` and all subdirectories to $PATH
export PATH="$PATH:$(du "$HOME/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//'):/usr/local/go/bin:$HOME/.local/bin/"
export EDITOR="emacsclient -c"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="vu"
export BIB="$HOME/Documents/LaTeX/uni.bib"
export REFER="$HOME/Documents/referbib"
export SUDO_ASKPASS="$HOME/.scripts/tools/dmenupass"
export NOTMUCH_CONFIG="$HOME/.config/notmuch-config"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"
